"""
Centralized message system for user-facing messages.

This module provides a type-safe, centralized location for all user-facing messages
used throughout the application. Messages are organized in a hierarchical structure
matching their usage context.
"""

# from typing import Any, Dict, List, Optional


class Messages:
    """Base class for all user-facing messages."""

    class Command:
        """
        Command-related messages.

        Note: The `!help` command is automatically generated by discord.py
        and does not have its own message strings here.
        """

        class Shared:
            """Messages shared across multiple commands."""

            INVALID_INDEX = "❌ Invalid index. Must be between 1 and {max_index}."
            """Format parameters:
            - max_index: int - The maximum valid index
            """

            INVALID_TARGET_INDEX = "❌ Invalid target index. Please provide a number."
            """No format parameters."""

            INVALID_INDEX_NUMBER = (
                "❌ Invalid index. Please provide a number, not text."
            )
            """No format parameters."""

            NO_TARGETS = "No monitoring targets have been added to this channel. Use `!add` to begin."
            """No format parameters."""

            INVALID_RADIUS = "❌ Radius must be between 1 and 100 miles"
            """No format parameters."""

            INVALID_COORDS = "❌ Invalid coordinates. Latitude must be -90 to 90, longitude -180 to 180"
            """No format parameters."""

        class Add:
            """Messages for the add command."""

            SUCCESS = "✅ Added {target_type}: **{display_name}** - Monitoring started!"
            """Format parameters:
            - target_type: str - Type of target (location, coordinates, city)
            - display_name: str - Name or identifier of the target
            """

            ERROR = "❌ Error adding {target_type}: {error_message}"
            """Format parameters:
            - target_type: str - Type of target (location, coordinates, city)
            - error_message: str - Error message to display
            """

            INVALID_TYPE = "❌ Invalid target type"
            """No format parameters."""

            NO_LOCATIONS = "❌ No locations found matching '{search_term}'"
            """Format parameters:
            - search_term: str - The search term that was used
            """

            SUGGESTIONS = "Location '{search_term}' not found directly. Did you mean one of these?\n{suggestions}\n\nPlease use `!add location <ID>` with the ID of the correct location."
            """Format parameters:
            - search_term: str - The search term that was used
            - suggestions: str - List of suggested locations
            """

            CITY_SUGGESTIONS = "Multiple cities found for '{city_name}'. Please be more specific:\n{suggestions}"
            """Format parameters:
            - city_name: str - The city name that was searched
            - suggestions: str - List of suggested city names
            """

            MISSING_LOCATION = "❌ Please provide a location name or ID. Usage: `!add location <name_or_id>`"
            MISSING_COORDS = "❌ Please provide latitude and longitude. Usage: `!add coordinates <lat> <lon> [radius]`"
            INVALID_COORDS_FORMAT = (
                "❌ Invalid coordinates. Please provide valid numbers."
            )
            MISSING_CITY = (
                "❌ Please provide a city name. Usage: `!add city <name> [radius]`"
            )
            INVALID_SUBCOMMAND = "❌ Invalid subcommand. Use `!add location`, `!add city`, or `!add coordinates`."
            """No format parameters."""

            LOCATION_NOT_FOUND = "❌ Location ID {location_id} not found. Please check the ID on PinballMap.com."
            """Format parameters:
            - location_id: int - The location ID that was not found
            """

            CITY_NOT_FOUND = "❌ Could not find coordinates for city: {city_name}"
            """Format parameters:
            - city_name: str - The city name that was not found
            """

            NO_RESULTS = "❌ No results found for: {search_term}"
            """Format parameters:
            - search_term: str - The search term that yielded no results
            """

            RADIUS_UPDATED = "✅ Updated radius to {radius} miles for existing coordinates: **{display_name}**"
            """Format parameters:
            - radius: int - The new radius in miles
            - display_name: str - The display name of the target
            """

            NOT_FOUND = "❌ {target_type} '{display_name}' not found"
            """Format parameters:
            - target_type: str - Type of target (location, coordinates, city)
            - display_name: str - Name of the target that was not found
            """

            MULTIPLE_RESULTS = "Multiple {target_type} found for '{display_name}'. Please be more specific:\n{results}"
            """Format parameters:
            - target_type: str - Type of target (location, coordinates, city)
            - display_name: str - Name of the target that was searched
            - results: str - List of matching results
            """

        class Remove:
            """Remove command messages."""

            SUCCESS = "✅ Removed {target_type} target: {display_name}"
            """Format parameters:
            - target_type: str - The type of target being removed
            - display_name: str - The name of the target being removed
            """

            MISSING_INDEX = "❌ Please provide an index number. Usage: `!rm <index>`\nUse `!list` to see target indices."
            """No format parameters."""

        class List:
            """List command messages."""

            TARGETS_TABLE = "```\n{targets_table}\n```\n\nChannel defaults: Poll rate: {poll_rate} minutes, Notifications: {notification_types}\n\nUse `!rm <index>` to remove a target"
            """Format parameters:
            - targets_table: str - A formatted table of targets
            - poll_rate: int - The channel's default poll rate
            - notification_types: str - The channel's default notification types
            """

        class Check:
            """Check command messages."""

            NEW_SUBMISSIONS = "✅ Found {count} new submission(s) since the last check:\n{submissions}"
            """Format parameters:
            - count: int - Number of new submissions
            - submissions: str - Formatted list of new submissions
            """

            RECENT_SUBMISSIONS = "ℹ️ No new submissions were found. Here are the {count} most recent activities:\n{submissions}"
            """Format parameters:
            - count: int - Number of recent submissions shown
            - submissions: str - Formatted list of recent submissions
            """

            NO_SUBMISSIONS_YET = "🤔 No submissions found for any of your targets yet. When there is activity on PinballMap.com, it will appear here."
            """No format parameters."""

            SUPPLEMENTAL_HEADER = "\n---\n*Most recent previously seen submissions:*\n"
            """No format parameters."""

        class Export:
            """Export command messages."""

            NO_TARGETS = "No targets to export. Use `!add` to add some first."
            CONFIGURATION = "Here is the configuration for this channel:\n\n{channel_config}\n\n{targets}"
            """Format parameters:
            - channel_config: str - Channel configuration commands
            - targets: str - Target configuration commands
            """
            HEADER = "**Export Commands:**\n```\n{commands}\n```"
            """Format parameters:
            - commands: str - List of commands to export
            """

        class PollRate:
            """Messages for the poll rate command."""

            SUCCESS_TARGET = (
                "✅ Set poll rate to {minutes} minutes for target {target_id}"
            )
            """Format parameters:
            - minutes: int - Poll rate in minutes
            - target_id: int - Target index
            """

            SUCCESS_CHANNEL = (
                "✅ Set default poll rate to {minutes} minutes for all targets"
            )
            """Format parameters:
            - minutes: int - Poll rate in minutes
            """

            ERROR = "❌ Please provide a valid number of minutes"
            """No format parameters."""

            INVALID_RATE = "❌ Poll rate must be at least 1 minute"
            """No format parameters."""

        class Notifications:
            """Messages for the notifications command."""

            SUCCESS_TARGET = (
                "✅ Set notifications to {notification_type} for target {target_id}"
            )
            """Format parameters:
            - notification_type: str - Type of notifications (machines, comments, all)
            - target_id: int - Target index
            """

            SUCCESS_CHANNEL = (
                "✅ Set default notifications to {notification_type} for all targets"
            )
            """Format parameters:
            - notification_type: str - Type of notifications (machines, comments, all)
            """

            ERROR = "❌ Invalid notification type. Use: {valid_types}"
            """Format parameters:
            - valid_types: str - Comma-separated list of valid notification types
            """

        class Error:
            """Error messages."""

            COMMAND = "❌ An unexpected error occurred while running `!{command}`. Please check the logs or contact the admin."
            """Format parameters:
            - command: str - Name of the command that failed
            """

            GENERAL = "❌ An unexpected error occurred: {error}"
            """Format parameters:
            - error: str - Error message
            """

    class Notification:
        """Notification-related messages."""

        class Machine:
            """Machine-related notifications."""

            ADDED = "🎮 **{machine_name}** added at **{location_name}** by {user_name}"
            """Format parameters:
            - machine_name: str - Name of the machine
            - location_name: str - Name of the location
            - user_name: str - Name of the user who added it
            """

            REMOVED = (
                "🗑️ **{machine_name}** removed from **{location_name}** by {user_name}"
            )
            """Format parameters:
            - machine_name: str - Name of the machine
            - location_name: str - Name of the location
            - user_name: str - Name of the user who removed it
            """

            MULTIPLE_ADDED = (
                "🎮 **{count} New Pinball Machines Added!**\n{machines}{remaining_text}"
            )
            """Format parameters:
            - count: int - Number of machines added
            - machines: str - List of machines added
            - remaining: int - Number of additional machines not shown
            """

            MULTIPLE_REMOVED = (
                "🗑️ **{count} Pinball Machines Removed:**\n{machines}{remaining_text}"
            )
            """Format parameters:
            - count: int - Number of machines removed
            - machines: str - List of machines removed
            - remaining: int - Number of additional machines not shown
            """

            REMAINING_MACHINES = "... and {count} more machines"
            """Format parameters:
            - count: int - Number of additional machines not shown
            """

        class Condition:
            """Condition-related notifications."""

            UPDATED = "🔧 **{machine_name}** at **{location_name}**{comment_text} - by {user_name}"
            """Format parameters:
            - machine_name: str - Name of the machine
            - location_name: str - Name of the location
            - comment_text: str - The full comment text, including a leading newline and icon if applicable
            - user_name: str - Name of the user who updated it
            """

        class Initial:
            """Initial notification messages."""

            FOUND = "✅ Found {count} recent submission(s) for **{display_name}**:"
            """Format parameters:
            - count: int - Number of submissions found
            - display_name: str - Name or identifier of the target
            """

            NONE = "ℹ️ No recent submissions found for **{display_name}**."
            """Format parameters:
            - display_name: str - Name or identifier of the target
            """

    class System:
        """System-related messages."""

        class Error:
            """Error messages."""

            UNEXPECTED = "❌ An unexpected error occurred while running the command"
            """No format parameters."""

            RESPONSE_MISSING_FIELD = "Response missing '{field}' field"
            """Format parameters:
            - field: str - Name of the missing field
            """

            DATA_MISSING_FIELD = "{data_type} data missing '{field}' field"
            """Format parameters:
            - data_type: str - Type of data (e.g., "Location", "Submission")
            - field: str - Name of the missing field
            """

            INVALID_TIMESTAMP = "Invalid timestamp format: {timestamp}"
            """Format parameters:
            - timestamp: str - The invalid timestamp string
            """

            INVALID_COORDINATE_TYPE = (
                "Invalid {coord_type} type: expected number, got {type}"
            )
            """Format parameters:
            - coord_type: str - Type of coordinate ("Latitude" or "Longitude")
            - type: type - Actual type received
            """
